### PR TITLE
Reimbursement

### PR DESCRIPTION
**Pull request by allisoninman**
Still needs to redirect to the home page on submit and show a successful, will wait until other PRs are merged and make a separate PR.

### CODE REVIEW

**Comment by allisoninman** [comment]
image

**Comment by allisoninman** [comment]
image
With errors on submit when input isn't valid

**Review by fitzmill — CHANGES_REQUESTED** [review]
Could you add a note next to the submit button saying that the request will be sent to the RSO advisor? It's on our list of changes we said we would make to the app

**Comment by allisoninman** [comment]
@fitzmill Done

**Review by fitzmill — APPROVED** [review]

**Pull request merged**
