### PR TITLE
Dashboard

### LINKED ISSUE #1: Dashboard

### PR DESCRIPTION
**Pull request by skmshaffer**
Implements the Dashboard Page: 
- Adds new notificationServices.js file with functions for changing and viewing system notifications. 
- Updates RSO model with identifier for routing purposes. 
- Added new components for Notification Card and RSO Card
- Implemented routing on RSO Card so that selecting an action triggers a redirect. 

Screenshot 2019-10-22 at 11 55 10 AM

Closes #1

### CODE REVIEW

**Review by allisoninman — COMMENTED** [review]
This looks awesome! 

One thing, when I redirect from the dropdown to the reimbursement or epr, I can't hit the back button on my browser to go back to the home page. I can use the back button when I redirect to the organization page and try to go back to the home page. Do you know why this would be?

**Comment by skmshaffer** [comment]
@allisoninman Thanks Alli! 

Great catch, I had forgotten to add a prop to the redirect that meant it wouldn't add to the navigation stack and would instead replace the item on top. I have since updated and it should work as expected!

**Comment by allisoninman** [comment]
@skmshaffer Nice it works now! I'm good to merge this whenever (and the sooner the better because it will make my life easier on my last task)

**Review by allisoninman — APPROVED** [review]

**Review by fitzmill — COMMENTED** [review]
This might not be necessary, but adding a little `x` button in the top right corner of the notification to make it dismissible might be good

**Review by gauriramesh — APPROVED** [review]
I am good to merge this so Alli can start on her stuff, but a couple of small things I noticed:
1. On your screenshot when you hover over one of the options in the dropdown, it highlights it in red. When I run it (I'm using Chrome) it highlights it in light grey, not sure why this is different, but just a thing I noticed.
2. Super nitpicky, but I think I would prefer if the contents of the membership cards were all black. To me the "I would like to" looks like it's a box I can type in (because it's grey, so it looks like a placeholder for an input box), and the "Go to membership" looks unclickable because it's grey.

**Pull request merged**
